server:
  port: 9999
  # 配置静态资源启用 gzip 压缩
  compression:
    enabled: true
    min-response-size: 128
# 配置主数据源
spring:
  # 配置redis数据源
#  redis:
#    host: localhost
#    port: 6379
#    database: 4
#    timeout: 5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/magic?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: zyl123
#  data:
    # 配置mongo数据源
#    mongodb:
#      host: localhost
#      port: 27017
#      database: magicapi
#      username: magicapi
#      password: 123456


magic-api:
  web: /magic/web
  show-sql: true #配置打印SQL
  compile-cache-size: 500 #配置编译缓存容量
  support-cross-domain: true # 跨域支持，默认开启
#  swagger:
#    version: 1.0
#    description: MagicAPI 接口信息
#    title: MagicAPI Swagger Docs
#    name: MagicAPI 接口
#    location: /v2/api-docs/magic-api/swagger2.json
  backup: #备份相关配置
    enable: true #是否启用
    max-history: -1 #备份保留天数，-1为永久保留
    table-name: magic_backup_record_v2 #使用数据库存储备份时的表名
  resource:
    type: database  # 配置接口存储方式，这里选择存在数据库中
    table-name: magic_api_file_v2  # 数据库中的表名
    prefix: /magic-api  # 前缀
#    location: classpath:magic-api
# 其它配置请参考 https://ssssssss.org/magic-api/config/
